modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
[[mods]]
modId = "more_decorative_blocks"
version = "${mod_version}"
displayName = "More Decorative Blocks"
displayURL = "https://github.com/MBI-Team/More-Decorative-Blocks"
logoFile= "more_decorative_blocks.png"
credits = "MBI-Team"
authors = "danhuangsu, Kush_Shul, z.h, Voyagerstar, huangyihao"
description = '''More Decorative Blocks is a Minecraft mod that to add more decorative blocks in the Minecraft.
You can use more blocks of it to build better building.
We hope they can help you to build the building.'''
[[dependencies."more_decorative_blocks"]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."more_decorative_blocks"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.0,1.22)"
ordering = "NONE"
side = "BOTH"
